# MongoDB Configuration
MONGODB_URL: "mongodb://localhost:27017"
DATABASE_NAME: "pogo_db"

# QDRANT Configuration
QDRANT_URL: "https://77fbc038-b2b1-4c42-9cb6-de580f918fdc.us-east4-0.gcp.cloud.qdrant.io"

# Test IDs (to be removed later)
TEST_USER_ID: "680aa1ab699c5f89ec8dda8f"
TEST_PROJECT_ID: "67f092a01f1e60f7ed5e4724"
TEST_SESSION_ID: "680aa1ab699c5f89ec8dda91"

# Storage Configuration
STORAGE_PATH: "storage"

# Processing Settings
AUDIO_CHUNK_SIZE: 1024
IMAGE_MAX_SIZE: [1920, 1080]

# File Size Limits
MAX_AUDIO_SIZE_MB: 500
MAX_IMAGE_SIZE_MB: 50
MAX_AUDIO_DURATION_HOURS: 3

# Background Processing
REDIS_URL: "redis://localhost:6379/0"
CELERY_WORKER_CONCURRENCY: 4
CELERY_TASK_TIMEOUT: 1800  # 30 minutes
CELERY_RETRY_ATTEMPTS: 3
CELERY_RETRY_DELAY: 60

# Search Configuration
ELASTICSEARCH_URL: "http://localhost:9200"
ELASTICSEARCH_USERNAME: ""
ELASTICSEARCH_PASSWORD: ""
SEARCH_INDEX_NAME: "pogo_artifacts"
SEARCH_MAX_RESULTS: 100

# Vector Store Configuration
vector_store:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  collection_name: "session_docs"
  vector_size: 1536  # OpenAI embedding size
  distance: "cosine"

# Firebase Configuration
firebase:
  project_id: "${FIREBASE_PROJECT_ID}"
  service_account_path: "${FIREBASE_SERVICE_ACCOUNT_PATH}"
  credentials_json: "${FIREBASE_CREDENTIALS}"

# JWT Configuration
jwt:
  secret_key: "${JWT_SECRET_KEY}"
  expiration_hours: 24

# LLM Configuration
llm:
  # Available providers: openai, gemini, anthropic
  provider: "openai"
  
  # API Keys (should be set via environment variables)
  api_keys:
    openai: "${OPENAI_API_KEY}"
    gemini: "${GEMINI_API_KEY}"
    anthropic: "${ANTHROPIC_API_KEY}"
  
  # Model configurations
  models:
    openai:
      image_analysis: "gpt-4o"  #deprecated gpt-4-vision-preview
      audio_transcription: "whisper-1"
      text_processing: "gpt-4-0125-preview"
      embeddings: "text-embedding-3-small"
      max_tokens: 2000
      temperature: 0.7
    
    gemini:
      image_analysis: "gemini-pro-vision"
      audio_transcription: "gemini-pro"
      text_processing: "gemini-pro"
      embeddings: "embedding-001"
      max_tokens: 2048
      temperature: 0.7
    
    anthropic:
      image_analysis: "claude-3-opus-20240229"
      audio_transcription: "claude-3-opus-20240229"
      text_processing: "claude-3-opus-20240229"
      embeddings: "claude-3-opus-20240229"
      max_tokens: 4096
      temperature: 0.7

  # Processing settings
  processing:
    audio_time_window_minutes: 5
    chunk_size: 5
    max_retries: 3
    retry_delay: 1 