name: pogo-backend
services:
  - name: pogo-api
    source_dir: /pogoapi
    github:
      repo: your-username/pogo-react
      branch: main
    run_command: gunicorn main:app
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
  - name: pogo-celery-worker
    source_dir: /pogoapi
    github:
      repo: your-username/pogo-react
      branch: main
    run_command: celery -A celery_app worker --loglevel=info --concurrency=2
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: MONGODB_URI
        value: mongodb+srv://roshangehlot500:roshan99999@pogo.ieempom.mongodb.net/?retryWrites=true&w=majority&appName=pogo
      - key: OPENAI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FIREBASE_PROJECT_ID
        value: hellopogo-529ca
      - key: FIREBASE_CREDENTIALS
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: QDRANT_URL
        value: https://73af5a51-332f-4b67-b98e-d9a3c73a5729.us-west-2-0.aws.cloud.qdrant.io:6333
      - key: QDRANT_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CELERY_BROKER_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: CELERY_RESULT_BACKEND
        scope: RUN_AND_BUILD_TIME
        type: SECRET

databases:
  - name: pogo-redis
    engine: REDIS
    version: "6"
    size: db-s-1vcpu-1gb 